-- ADMINPAGELIST
select * from adminpagelist;

INSERT INTO adminpagelist
(LISTID, PRODUCT_ID, DELIVERY_ID, RANGKING, SALES)
VALUE
('1', 'PROD_1', '1', 2, 500000)
;

INSERT INTO adminpagelist
(LISTID, PRODUCT_ID, DELIVERY_ID, RANGKING, SALES)
VALUE
('2', 'PROD_2', '2', 1, 600000)
;

DELETE FROM adminpagelist
WHERE LISTID='1'
;

UPDATE adminpagelist 
SET LISTID = 2 
WHERE SALES = 650000
;