
CREATE TABLE COORDINATION_INFO
(
  COORDINATION_ID   VARCHAR(100) NOT NULL COMMENT '코디게시글ID',
  BULLETIN_NO       VARCHAR(100) NULL     COMMENT '게시글번호',
  PICTURE           VARCHAR(100) NULL     COMMENT '사진',
  USERNAME          VARCHAR(100) NULL     COMMENT '이름',
  HEIGHT            VARCHAR(100) NULL     COMMENT '키',
  WEIGHT            VARCHAR(100) NULL     COMMENT '나이',
  JOB               VARCHAR(100) NULL     COMMENT '게시글 내용',
  PRODUCT_ID        VARCHAR(100) NULL     COMMENT '참조제품ID',
  VIEWS             VARCHAR(100) NULL     COMMENT '조회수',
  DATE              VARCHAR(100) NULL     COMMENT '작성날짜',
  MODIFICATION_DATE VARCHAR(100) NULL     COMMENT '수정날짜',
  LIKES             VARCHAR(100) NULL     COMMENT '좋아요수',
  PRIMARY KEY (COORDINATION_ID)
) COMMENT '코디정보';
