SELECT * FROM COORDINATION_INFO
-- WHERE COORDINATION_ID = ''
;

INSERT INTO COORDINATION_INFO
(COORDINATION_ID, BULLETIN_NO, PICTURE, USERNAME, HEIGHT, WEIGHT, JOB, PRODUCT_ID, VIEWS, DATE, MODIFICATION_DATE, LIKES)
VALUES
('CORD_1', '1', 'SDKSDKM2324LMSD', '김다미', '170', '50', '배우', 'PROD_1', '0', SYSDATE(), SYSDATE(), '0');

DELETE FROM COORDINATION_INFO
WHERE COORDINATION_ID='CORD_1'
;

UPDATE COORDINATION_INFO
SET USERNAME='홍길동'
WHERE COORDINATION_ID='CORD_1'
;