SELECT * FROM ORDERLIST
WHERE ORDER_ID = 'ORDER_01'
;

INSERT INTO ORDERLIST
(ORDER_ID, USERNAME, EMAIL, PHONENUMBER, ORDERDATE, DELIVERY_ADDRESS, PRODUCT_ID, PRICE, ORDER_METHOD)
VALUES
('ORDER_01', '김민수', 'minsu01@naver.com', '010-1234-1234', SYSDATE(), '경기도 화성시 반송동', 'PROD_1', '1200', '카드');

DELETE FROM ORDERLIST
WHERE ORDER_ID='ORDER_01'
;

UPDATE ORDERLIST
SET USERNAME='홍길동'
WHERE ORDER_ID='ORDER_01'
;