
CREATE TABLE ORDERLIST
(
  ORDER_ID         VARCHAR(100) NOT NULL COMMENT '주문ID',
  USERNAME         VARCHAR(100) NULL     COMMENT '이름',
  EMAIL            VARCHAR(100) NULL     COMMENT '이메일',
  PHONENUMBER      VARCHAR(100) NULL     COMMENT '전화번호',
  ORDERDATE        VARCHAR(100) NULL     COMMENT '주문날짜',
  DELIVERY_ADDRESS VARCHAR(100) NULL     COMMENT '배송지',
  PRODUCT_ID       VARCHAR(100) NULL     COMMENT '상품ID',
  PRICE            VARCHAR(100) NULL     COMMENT '구매가격',
  ORDER_METHOD     VARCHAR(100) NULL     COMMENT '결제방법',
  PRIMARY KEY (ORDER_ID)
) COMMENT '주문';
