
CREATE TABLE SHOPPINGCART
(
  SHOPPINGCART_ID    VARCHAR(100) NOT NULL COMMENT '쇼핑카트리스트ID',
  SHOPPINGCART_ORDER VARCHAR(100) NULL     COMMENT '쇼핑카트리스트순서',
  PRODUCT_ID         VARCHAR(100) NULL     COMMENT '상품ID',
  PRODUCT_COUNT      VARCHAR(100) NULL     COMMENT '상품개수',
  PRIMARY KEY (SHOPPINGCART_ID)
) COMMENT '쇼핑카트 리스트';

DROP TABLE SHOPPINGCART;