SELECT * 
FROM SHOPPINGCART 
WHERE SHOPPINGCART_ID = 'SC01'
;

INSERT INTO SHOPPINGCART
(SHOPPINGCART_ID, SHOPPINGCART_ORDER, PRODUCT_ID, PRODUCT_COUNT)
VALUES
('SC01', '1', 'PROD_1', '1')
;

UPDATE SHOPPINGCART
SET PRODUCT_COUNT = '2'
WHERE SHOPPINGCART_ID='SC01'
;

DELETE FROM SHOPPINGCART
WHERE SHOPPINGCART_ID='SC01'
;