SELECT * 
FROM SHOPPINGCART 
WHERE SHOPPINGCART_ID = 'SC01'
;

SELECT * 
FROM SHOPPINGCART 
ORDER BY DATE
;
SELECT SHOPPINGCART_ID, PRODUCT_ID, PRODUCT_COUNT, DATE, B.*
FROM SHOPPINGCART A JOIN USER B 
WHERE A.UID = B.UID 
;

SELECT * FROM PRODUCT;

SELECT C.*, BRAND, CLOTHES_NAME, PRICE, CATEGORY, DISCOUNT_RATE
FROM (SELECT SHOPPINGCART_ID, PRODUCT_ID, PRODUCT_COUNT, DATE, B.*
FROM SHOPPINGCART A JOIN USER B 
ON A.UID = B.UID AND A.UID='U0001' ) AS C JOIN product AS D
ON C.PRODUCT_ID = D.PRODUCT_ID
;

SELECT * 
FROM (SELECT C.*, BRAND, CLOTHES_NAME, PRICE, CATEGORY, DISCOUNT_RATE
FROM (SELECT SHOPPINGCART_ID, PRODUCT_ID, PRODUCT_COUNT, DATE, B.*
FROM SHOPPINGCART A JOIN USER B 
ON A.UID = B.UID AND A.UID='U0001' ) AS C JOIN product AS D
ON C.PRODUCT_ID = D.PRODUCT_ID) AS SHOPPINGCARTINFO JOIN CIP_ATTACHFILE AS FILE
ON SHOPPINGCARTINFO.PRODUCT_ID = FILE.SOURCE_UNIQUE_SEQ 
-- AND SHOPPINGCARTINFO.PRODUCT_ID = 'PROD_1'
GROUP BY SOURCE_UNIQUE_SEQ
ORDER BY DATE
;

INSERT INTO SHOPPINGCART
(SHOPPINGCART_ID, SHOPPINGCART_ORDER, PRODUCT_ID, PRODUCT_COUNT)
VALUES
('SC01', '1', 'PROD_1', '1')
;

UPDATE SHOPPINGCART
SET PRODUCT_COUNT = '2'
WHERE SHOPPINGCART_ID='SC01'
;

DELETE FROM SHOPPINGCART
WHERE SHOPPINGCART_ID='SC01'
;