SELECT * FROM DELIVERY
WHERE DELIVERY_ID = 'DEL_1'
;

INSERT INTO DELIVERY
(DELIVERY_ID, DELIVERY_COMPANY, SHIPMENT_TIME, DELIVERY_STATUS, DELIVERY_ADDRESS)
VALUES
('DEL_1', 'CJ대한통운', SYSDATE(), '배송준비중', '경기도 화성시 반송동');

DELETE FROM DELIVERY
WHERE DELIVERY_ID = 'DEL_1'
;

UPDATE DELIVERY
SET DELIVERY_COMPANY='로젠택배'
WHERE DELIVERY_ID = 'DEL_1'
;