SELECT * FROM DELIVERY
WHERE DELIVERY_ID = 'DEL_1'
;

SELECT * FROM DELIVERY
;


INSERT INTO DELIVERY
(DELIVERY_ID, DELIVERY_COMPANY, SHIPMENT_TIME, DELIVERY_STATUS, DELIVERY_ADDRESS, USERNAME, PHONENUMBER, REQUIREMENT)
VALUES
('DEL_1', 'CJ대한통운', SYSDATE(), '배송준비중', '경기도 화성시 반송동', '홍길동','010-2342-3356','부재시 경비실에 맡겨주세요');

DELETE FROM DELIVERY
WHERE DELIVERY_ID = 'd6f280de-6ff8-4503-ad70-91aa4c1874dc'
;

UPDATE DELIVERY
SET DELIVERY_COMPANY='로젠택배'
WHERE DELIVERY_ID = 'DEL_1'
;