SELECT * FROM ORDERLIST
WHERE ORDER_ID = 'ORDER_01'
;
SELECT * FROM ORDERLIST
;

SELECT  A.SHOPPINGCART_ID, A.PRODUCT_COUNT, A.UID, A.DATE, B.*
FROM SHOPPINGCART A, PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND A.UID='U0001'
ORDER BY DATE
;


SELECT * 
FROM (SELECT  A.SHOPPINGCART_ID, A.PRODUCT_COUNT, A.UID, A.DATE, B.*
FROM SHOPPINGCART A, PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND A.UID='U0001') C, CIP_ATTACHFILE D
WHERE C.PRODUCT_ID = D.SOURCE_UNIQUE_SEQ
GROUP BY PRODUCT_ID
ORDER BY DATE
;

INSERT INTO ORDERLIST
(ORDER_ID,SHOPPINGCART_ID,DELIVERY_ID,ORDER_METHOD,FINAL_PRICE,ORDERDATE,ADDITIONAL_DISCOUNT)
VALUES
('ORDER_01','SC01','DEL_1','카드','54,000',SYSDATE(),'25');

DELETE FROM ORDERLIST
WHERE SHOPPINGCART_ID='SHOPPINGCART_ID'
;

UPDATE ORDERLIST
SET USERNAME='홍길동'
WHERE ORDER_ID='ORDER_01'
;