SELECT * FROM ORDERLIST
WHERE ORDER_ID = 'ORDER_01'
;

SELECT  A.SHOPPINGCART_ID, A.PRODUCT_COUNT, A.UID, A.DATE, B.*
FROM SHOPPINGCART A, PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND A.UID='U0001'
ORDER BY DATE
;


SELECT * 
FROM (SELECT  A.SHOPPINGCART_ID, A.PRODUCT_COUNT, A.UID, A.DATE, B.*
FROM SHOPPINGCART A, PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND A.UID='U0001') C, CIP_ATTACHFILE D
WHERE C.PRODUCT_ID = D.SOURCE_UNIQUE_SEQ
GROUP BY PRODUCT_ID
ORDER BY DATE
;

INSERT INTO ORDERLIST
(ORDER_ID, USERNAME, EMAIL, PHONENUMBER, ORDERDATE, DELIVERY_ADDRESS, PRODUCT_ID, PRICE, ORDER_METHOD)
VALUES
('ORDER_01', '김민수', 'minsu01@naver.com', '010-1234-1234', SYSDATE(), '경기도 화성시 반송동', 'PROD_1', '1200', '카드');

DELETE FROM ORDERLIST
WHERE SHOPPINGCART_ID='SHOPPINGCART_ID'
;

UPDATE ORDERLIST
SET USERNAME='홍길동'
WHERE ORDER_ID='ORDER_01'
;