CREATE TABLE COMMENT
(
  COMMENT_UID VARCHAR(100) NOT NULL COMMENT '댓글ID',
  UID         VARCHAR(100) NOT NULL COMMENT '유저ID',
  DATE        VARCHAR(100) NULL     COMMENT '작성날',
  CONTENT     VARCHAR(100) NULL     COMMENT '내용',
  PRIMARY KEY (COMMENT_UID)
) COMMENT '댓글';