INSERT INTO COMMENT
(COMMENT_UID,UID,DATE,SOURCE_UNIQUE_SEQ,CONTENT)
VALUES
('COM_1','U0001',SYSDATE(),'CORD_1','댓글1')
;

INSERT INTO COMMENT
(COMMENT_UID,UID,DATE,SOURCE_UNIQUE_SEQ,CONTENT)
VALUES
('COM_2','U0002',SYSDATE(),'CORD_1','댓글2')
;

INSERT INTO COMMENT
(COMMENT_UID,UID,DATE,SOURCE_UNIQUE_SEQ,CONTENT)
VALUES
('COM_3','U0003',SYSDATE(),'CORD_1','댓글3')
;

SELECT * 
FROM COMMENT;

DELETE FROM COMMENT
WHERE COMMENT_UID='3c4816f7-2da6-4981-abc7-0461b215b456';

SELECT * 
FROM COMMENT A, USER B
WHERE A.SOURCE_UNIQUE_SEQ = 'CORD_1' AND B.UID='U0003';
