SELECT * FROM CIP_ATTACHFILE;

SELECT * FROM CIP_ATTACHFILE
WHERE SOURCE_UNIQUE_SEQ = 'cord_1'
;

SELECT * FROM CIP_ATTACHFILE
WHERE SOURCE_UNIQUE_SEQ = 'cord_1'
GROUP BY SOURCE_UNIQUE_SEQ
;

INSERT INTO CIP_ATTACHFILE
        (ATTACHFILE_SEQ, SOURCE_UNIQUE_SEQ, ORGINALFILE_NAME, PHYSICALFILE_NAME, 
        REGISTER_SEQ, REGISTRY_DATE, MODIFIER_SEQ, MODIFY_DATE)
VALUES
		('UU11', 'CORD_1', 'model1.jpg','dami','REG1123',SYSDATE(),'MOD1122',SYSDATE())
;
INSERT INTO CIP_ATTACHFILE
        (ATTACHFILE_SEQ, SOURCE_UNIQUE_SEQ, ORGINALFILE_NAME, PHYSICALFILE_NAME, 
        REGISTER_SEQ, REGISTRY_DATE, MODIFIER_SEQ, MODIFY_DATE)
VALUES
		('UU14', 'CORD_1', 'model1_2.jpg','dami','REG1123',SYSDATE(),'MOD1122',SYSDATE())
;
INSERT INTO CIP_ATTACHFILE
        (ATTACHFILE_SEQ, SOURCE_UNIQUE_SEQ, ORGINALFILE_NAME, PHYSICALFILE_NAME, 
        REGISTER_SEQ, REGISTRY_DATE, MODIFIER_SEQ, MODIFY_DATE)
VALUES
		('UU15', 'CORD_1', 'model1_3.jpg','dami','REG1123',SYSDATE(),'MOD1122',SYSDATE())
;
INSERT INTO CIP_ATTACHFILE
        (ATTACHFILE_SEQ, SOURCE_UNIQUE_SEQ, ORGINALFILE_NAME, PHYSICALFILE_NAME, 
        REGISTER_SEQ, REGISTRY_DATE, MODIFIER_SEQ, MODIFY_DATE)
VALUES
		('UU16', 'CORD_1', 'model1_4.jpg','dami','REG1123',SYSDATE(),'MOD1122',SYSDATE())
;

INSERT INTO CIP_ATTACHFILE
        (ATTACHFILE_SEQ, SOURCE_UNIQUE_SEQ, ORGINALFILE_NAME, PHYSICALFILE_NAME, 
        REGISTER_SEQ, REGISTRY_DATE, MODIFIER_SEQ, MODIFY_DATE)
VALUES
		('UU12', 'CORD_2', 'model3.jpg','brian','REG1124',SYSDATE(),'MOD1123',SYSDATE())
;

INSERT INTO CIP_ATTACHFILE
        (ATTACHFILE_SEQ, SOURCE_UNIQUE_SEQ, ORGINALFILE_NAME, PHYSICALFILE_NAME, 
        REGISTER_SEQ, REGISTRY_DATE, MODIFIER_SEQ, MODIFY_DATE)
VALUES
		('UU13', 'CORD_3', 'model2.jpg','chulsu','REG1125',SYSDATE(),'MOD1124',SYSDATE())
;

UPDATE CIP_ATTACHFILE
SET ORGINALFILE_NAME='홍길동',
	PHYSICALFILE_NAME='',
    HEIGHT='',
    WEIGHT='',
    CORD_CONTENT='',
    MODIFICATION_DATE = SYSDATE(),
    JOB=''
WHERE COORDINATION_ID='CORD_1'
;

UPDATE CIP_ATTACHFILE
SET ORGINALFILE_NAME='홍길동'
WHERE ATTACHFILE_SEQ='UU11'
;

DELETE FROM CIP_ATTACHFILE
;

DELETE FROM CIP_ATTACHFILE
WHERE ATTACHFILE_SEQ='08ccb4be-5b02-49bd-93a7-57519d0353e8'
;
