SELECT * FROM PRODUCT;

SELECT * FROM PRODUCT
WHERE IS_BESTSELLING_PRODUCT = 'TRUE';

INSERT INTO PRODUCT
(PRODUCT_ID, PICTURE, BRAND, CLOTHES_NAME, PRICE, IS_BESTSELLING_PRODUCT)
VALUES('PROD_1','shop1.jpg','Giordano','남자상의',50000,'TRUE');

UPDATE PRODUCT
SET PRICE = 40000
WHERE PRODUCT_ID='PROD_1';

DELETE FROM PRODUCT
WHERE PRODUCT_ID='PROD_1';

