-- QNA
select * from qna;

INSERT INTO QNA
(POST_NO_QNA, UID, CATEGORY, TITLE, DATE, CONTENT)
VALUE
(1, 'U0002', 'FORWARD/DELIVERY', '배송 문의','2023-02-21', '배송은 얼마나 걸리나요')
;

INSERT INTO QNA
(POST_NO_QNA, UID, CATEGORY, TITLE, DATE, CONTENT)
VALUE
(2, 'U0003', 'ETC', '주문한거랑 색이 달라요','2023-01-25', '주문한 색이랑 다른 색이 왔어요')
;

DELETE FROM QNA
WHERE POST_NO_QNA='1'
;

UPDATE QNA 
SET POST_NO_QNA = 1 
WHERE TITLE = '배송 문의입니다.'
;

-- FAQ
select * from faq;

INSERT INTO FAQ
(POST_NO_FAQ, UID, CATEGORY, TITLE, DATE, CONTENT)
VALUE
(1, 'U0001', 'PURCHASE/CANCEL', '주문 취소 문의','2023-02-21', '주문을 취소싶은 경우에는 회사 전화로 문의주세요.')
;

INSERT INTO FAQ
(POST_NO_FAQ, UID, CATEGORY, TITLE, DATE, CONTENT)
VALUE
(2, 'U0001', 'ETC', '사이즈 문의','2023-01-25', '사이즈는 정사이즈 입니다.')
;

DELETE FROM FAQ
WHERE POST_NO_FAQ='1'
;

UPDATE FAQ 
SET POST_NO_FAQ = 2 
WHERE TITLE = '사이즈 문의입니다.'
;

-- ANNOUNCEMENT
select * from announcement;

INSERT INTO ANNOUNCEMENT
(POST_NO_ANNO, UID, CATEGORY, TITLE, DATE, CONTENT)
VALUE
(1, 'U0001', 'ETC', '색상 추가','2023-02-21', '제품의 색상이 추가됐습니다.')
;

INSERT INTO ANNOUNCEMENT
(POST_NO_ANNO, UID, CATEGORY, TITLE, DATE, CONTENT)
VALUE
(2, 'U0001', 'FORWARD/DELIVERY', '설 배송 지연','2023-01-25', '설 연휴동안은 배송이 지연될 예정입니다.')
;

DELETE FROM ANNOUNCEMENT
WHERE POST_NO_ANNO='1'
;

UPDATE ANNOUNCEMENT 
SET POST_NO_ANNO = 2 
WHERE TITLE = '설 연휴기간 배송 지연 안내'
;