-- announcement
SELECT * FROM ANNOUNCEMENT;                     -- 전체
SELECT CHANGE/RETURN/REPAIR FROM ANNOUNCEMENT;  -- 교환/반품/수선
SELECT PURCHASE/CANCEL FROM ANNOUNCEMENT;       -- 주문/취소
SELECT ECT FROM ANNOUNCEMENT;                   -- 기타

-- BOARD SELECT
SELECT TITLE,WRITER,DATE,CONTENT FROM ANNOUNCEMENT;

INSERT INTO ANNOUNCEMENT
(`POST_NO`, `CATEGORY`, `TITLE`, `WRITER`, `DATE`)
VALUES
('1', 'ECT', 'TITLE1', 'ID1', '2023-01-05')
;

UPDATE ANNOUNCEMENT
SET TITLE='TITLE2',DATE='2023-02-16'
;

-- FAQ
SELECT * FROM FAQ;                      -- 전체
SELECT CHANGE/RETURN/REPAIR FROM FAQ;   -- 교환/반품/수선
SELECT PURCHASE/CANCEL FROM FAQ;        -- 주문/취소
SELECT ECT FROM FAQ;                    -- 기타

-- BOARD SELECT
SELECT TITLE,WRITER,DATE,CONTENT FROM FAQ;

INSERT INTO FAQ
(`POST_NO`, `CATEGORY`, `TITLE`, `WRITER`, `DATE`)
VALUES
('1', 'ECT', 'TITLE1', 'ID1', '2023-01-05')
;

UPDATE FAQ
SET TITLE='TITLE2',DATE='2023-02-16'
;

-- QNA
SELECT * FROM QNA;                      -- 전체
SELECT CHANGE/RETURN/REPAIR FROM QNA;   -- 교환/반품/수선
SELECT PURCHASE/CANCEL FROM QNA;        -- 주문/취소
SELECT ECT FROM QNA;                    -- 기타

-- BOARD SELECT
SELECT TITLE,WRITER,DATE,CONTENT FROM QNA;

INSERT INTO QNA
(`POST_NO`, `CATEGORY`, `TITLE`, `WRITER`, `DATE`)
VALUES
('1', 'ECT', 'TITLE1', 'ID1', '2023-01-05')
;

UPDATE QNA
SET TITLE='TITLE2',DATE='2023-02-16'
;